### PR TITLE
LJH version 2.2 files

### PR DESCRIPTION
**Pull request by joefowler**
Hi Galen,

Consider testing (first) and then pulling this branch. It's supposed to be able to read LJH 2.2 files. On he other hand, if you aren't keen to test it yourself, I can at least try to make sure that it reads an actual v2.2 files. I just got such a set of files from Kelsey. Still, that's only a minimal test.

Also, of course, you'll want to make sure that all your other code is compatible with this one. In the latest commit, I did try to make the obvious things in steps.jl be compatible with the new API, but who knows. I can't say that your code is, um, thoroughly documented. (Yes, I know that it started as a quick test. Don't they all?)

### CODE REVIEW

**Comment by joefowler** [comment]
Okay, a simple f=LJHFile("filename.ljh") and then plot(f[1][1]) does not look right. Better not merge yet...

**Comment by ggggggggg** [comment]
A simple test would be to write known data to Ljubljana (that's the
autocorrect for ljh), then read it back out and check that it is equal.

**Comment by joefowler** [comment]
Galen: I now have a working test suite for the LJH module (see test/ljh.jl). This tests both the file writer and reader. Files are written in /tmp of both versions LJH 2.1.0 and 2.2.0. The reader tests 
- LJHFile access by `ljh[i]`
- LJHSlice access by `ljhslice = ljh[i:j]; ljhslice[i]`
- LJHGroup where multiple files make a group, including groups made from 1 file or 3, and including groups initialized by file name or by open LJHFile object.

Other tests _not_ yet done include the `pop!(LJHFile,...)` method and `fileRecords(LJHFile,...)` method. If you want, I can test those before you accept this pull request.

**Comment by joefowler** [comment]
Ignore my previous statement about incomplete coverage. I pushed an improvement. The LJH module tests cover `pop!()`, `fileRecords()`, and `LJHRewind()`.

**Comment by ggggggggg** [comment]
I think we should go ahead and conform to Julia style guidelines. Mainly
use all lowercase for functions, and underscore if necessary.

**Comment by joefowler** [comment]
Fine. See commit 2b40ef5964285f5788815b26d94a4cd1aab8c985

**Comment by ggggggggg** [comment]
Looks good. I'll merge it when I'm ready to fix my code to deal with it.

**Comment by ggggggggg** [comment]
The only problem was that you had changed the definition of  `TwoExponentialPulseGenerator` without finishing the job. Due to the magic of `zip` I didn't even need to change any of my other code to use the newly return `timestamp` because `zip` still just grabbed the first two items.

**Pull request merged**
